NAMESPACE=$(echo $NAMESPACE)
APP_DOMAIN=$(echo $APP_DOMAIN)
API_DOMAIN=$(echo $API_DOMAIN)
GOOGLE_API_KEY=$(echo $GOOGLE_API_KEY)
INSTALL_OPERATORS=true
HELM_INFRA_RELEASE_NAME=infra
HELM_APP_RELEASE_NAME=apps
DELETE_CRD=true


